"""fix user_evidence_config.expiry_time name

Revision ID: 18aa12c81635
Revises: d74697732052
Create Date: 2018-01-05 15:34:18.325999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18aa12c81635'
down_revision = 'd74697732052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_evidence_config', sa.Column('expire_time', sa.DateTime(), nullable=True))
    op.drop_column('user_evidence_config', 'expiryTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_evidence_config', sa.Column('expiryTime', mysql.DATETIME(), nullable=True))
    op.drop_column('user_evidence_config', 'expire_time')
    # ### end Alembic commands ###
