"""first

Revision ID: b010d11bfe59
Revises: 
Create Date: 2018-01-05 15:23:34.509237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b010d11bfe59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_resource')
    op.drop_table('t_user')
    op.drop_table('t_evidence_back')
    op.drop_table('sys_organization')
    op.drop_table('user_evidence_config')
    op.drop_table('t_evidence')
    op.drop_table('sys_user')
    op.drop_table('sys_role')
    op.drop_table('sys_user_role')
    op.drop_table('sys_role_resource')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_role_resource',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('resource_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('update_time', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('sys_user_role',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('update_time', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_role',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status_code', mysql.SMALLINT(display_width=2), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('update_time', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('organization_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('salt', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('status_code', mysql.SMALLINT(display_width=2), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('allow_ips', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('is_org_admin', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('evidence_config_id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('update_time', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('t_evidence',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('file_md5', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('callback', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('upload_time', mysql.DATETIME(), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('file_size', mysql.INTEGER(display_width=128), autoincrement=False, nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=2), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('consumer', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('evidence_sign', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('zip_password', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=True),
    sa.Column('file_temp_path', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('status_code', mysql.SMALLINT(display_width=2), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user_evidence_config',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('evidence_count', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('storage_size', mysql.INTEGER(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('storage_used', mysql.INTEGER(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('storage_create_time', mysql.DATETIME(), nullable=True),
    sa.Column('expiryTime', mysql.DATETIME(), nullable=True),
    sa.Column('create_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('update_time', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_organization',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('country_code', mysql.VARCHAR(length=50), server_default=sa.text("'0'"), nullable=True),
    sa.Column('credential', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('credential_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status_code', mysql.SMALLINT(display_width=2), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('create_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('update_time', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('t_evidence_back',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('file_md5', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('callback', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('upload_time', mysql.DATETIME(), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('file_size', mysql.INTEGER(display_width=128), autoincrement=False, nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=2), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('consumer', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('evidence_sign', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('zip_password', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=True),
    sa.Column('file_temp_path', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('t_user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('login_email', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('user_type', mysql.INTEGER(display_width=2), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('credential_name', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('credential_code', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('status_code', mysql.TINYINT(display_width=2), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('country_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('allow_ips', mysql.VARCHAR(length=1024), server_default=sa.text("''"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_resource',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('type', mysql.SMALLINT(display_width=2), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('permission', mysql.VARCHAR(length=50), server_default=sa.text("'GET'"), nullable=True),
    sa.Column('status_code', mysql.SMALLINT(display_width=2), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('update_time', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
