"""created all

Revision ID: d74697732052
Revises: b010d11bfe59
Create Date: 2018-01-05 15:29:13.510245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74697732052'
down_revision = 'b010d11bfe59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sys_organization_parent_id'), 'sys_organization', ['parent_id'], unique=False)
    op.drop_index('idx_sys_organization_parent_id', table_name='sys_organization')
    op.create_index(op.f('ix_sys_resource_parent_id'), 'sys_resource', ['parent_id'], unique=False)
    op.drop_index('idx_sys_resource_parent_id', table_name='sys_resource')
    op.create_index(op.f('ix_sys_user_organization_id'), 'sys_user', ['organization_id'], unique=False)
    op.drop_index('idx_sys_user_organization_id', table_name='sys_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_sys_user_organization_id', 'sys_user', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_sys_user_organization_id'), table_name='sys_user')
    op.create_index('idx_sys_resource_parent_id', 'sys_resource', ['parent_id'], unique=False)
    op.drop_index(op.f('ix_sys_resource_parent_id'), table_name='sys_resource')
    op.create_index('idx_sys_organization_parent_id', 'sys_organization', ['parent_id'], unique=False)
    op.drop_index(op.f('ix_sys_organization_parent_id'), table_name='sys_organization')
    # ### end Alembic commands ###
